PRAGMA foreign_keys = ON;

CREATE TABLE dogs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL,
  age INTEGER NOT NULL,
  skills VARCHAR(255) NOT NULL,
  picture_url VARCHAR(255) NOT NULL
);

